### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by rontornambe** [ikkez/f3-opauth#3]
When I try to run this plugin, I get the following error:

[10-Jun-2016 13:39:45 UTC] PHP Fatal error:  Class 'Prefab' not found in /home/deje/public_html/writers-tryst-test/php/f3-oauth/OpauthBridge.php on line 18
[10-Jun-2016 13:39:45 UTC] PHP Stack trace:
[10-Jun-2016 13:39:45 UTC] PHP   1. {main}() /home/deje/public_html/writers-tryst-test/index.php:0
[10-Jun-2016 13:39:45 UTC] PHP   2. require() /home/deje/public_html/writers-tryst-test/index.php:2

**Comment by ikkez** [comment]
Looks like you have not included the fat free base.php, which is the required for all plugins of cause.

**Comment by rontornambe** [comment]
Here's my code:

require "php/f3-oauth/OpauthBridge.php";$f3 =
require('php/fatfree-master/lib/base.php');
 $f3->set('AUTOLOAD','php/f3-oauth/'); // add the opauth path to the
autoload $f3->config('php/f3-oauth/opauth.ini', true);$opauth =
OpauthBridge::instance($f3->opauth);header('Location:
http://writers-tryst.ron-tornambe.com/auth/facebook');
 // define login handler$opauth->onSuccess(function($data){
    header('Content-Type: text');
    echo 'User successfully authenticated.'."\n";
    print_r($data['info']);});
 // define error handler$opauth->onAbort(function($data){
    header('Content-Type: text');
    echo 'Auth request was canceled.'."\n";
    print_r($data);});$f3->run();

?>

I would much appreciate it if you would include a code sample for
calling logging in and calling facebook. Can I assume the domain.com
is the domain requesting authentication?

**Comment by ikkez** [comment]
The code is unreadable.. would you kindly add the proper formatting syntax to code samples next time? It's 3x backticks ( ` ) before and after the code block.

why did you add the header location redirect? It cannot work this way. You have to use that link on a button in your frontend somewhere, otherwise the auth process can never complete, since the user is redirected back to your site after authentication, which would initiate other auth again and end in a loop.

Do not require the opauthbride.php file. The autoloader should load it.
Loading any plugin before you require the base.php is not good idea either.

This is the full sample:
```php
<?php
$f3 = require('php/fatfree-master/lib/base.php');
$f3->set('AUTOLOAD','php/f3-oauth/'); 
$f3->config('php/f3-oauth/opauth.ini', true);
$opauth =OpauthBridge::instance($f3->opauth);
$opauth->onSuccess(function($data){
    header('Content-Type: text');
    echo 'User successfully authenticated.'."\n";
    print_r($data['info']);
});
$opauth->onAbort(function($data){
    header('Content-Type: text');
    echo 'Auth request was canceled.'."\n";
    print_r($data);
});
$f3->route('GET /',function(){
  echo "hallo";
});
$f3->run();
?>
```
Now go to your project, see if you get "hallo". Now add `auth/facebook` to start the auth with facebook or `auth/github` for the github provider. I recommend that you create your own apps, and put the new keys and secrets into the config file. the strategy docs have at least a link where you can find the dev tools for each provider to create and setup that apps / api keys.

**Comment by rontornambe** [comment]
Thanks so much for putting up with me. I finally got it working.
